/**
 * @author: dwi.setiyadi@gmail.com
*/

export const UPCOMINGCLASSFETCH = 'HOME.UPCOMINGCLASSFETCH';
export const UPCOMINGCLASSSUCCESS = 'HOME.UPCOMINGCLASSSUCCESS';
export const UPCOMINGCLASSFAILURE = 'HOME.UPCOMINGCLASSFAILURE';

export const PROFILEFETCH = 'HOME.PROFILEFETCH';
export const PROFILESUCCESS = 'HOME.PROFILESUCCESS';
export const PROFILEFAILED = 'HOME.PROFILEFAILED';


export const APISIGNIN = 'api/login';
